#!/usr/bin/env bash
# Builds the single-file LibreSprite diagnostic script (deterministic: plain
# concatenation of tracked sources, no timestamps).
# Usage: tools/build_libresprite.sh [output-dir]   (default: dist/libresprite)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="${1:-$ROOT/dist/libresprite}"
NAME="PixelProofreader-Diagnostic.js"
mkdir -p "$OUT_DIR"
{
  printf '%s\n' "// Pixel Proofreader 0.0.1-p0 - read-only diagnostic for LibreSprite 1.3."
  printf '%s\n' "// Generated by tools/build_libresprite.sh from src/libresprite/. Do not edit."
  printf '\n'
  cat "$ROOT/src/libresprite/core.js"
  printf '\n'
  cat "$ROOT/src/libresprite/main.js"
} > "$OUT_DIR/$NAME"
cd "$OUT_DIR"
sha256sum "$NAME" > "$NAME.sha256"
echo "$OUT_DIR/$NAME"
cat "$NAME.sha256"
